#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
sxhkd &

# panel
tint2 -c ~/.config/tint2/tint2rc & 

# Set some bsp specific stuff
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focused_border_color \#423e3d
bspc config window_gap 12
bspc config border_width 2

bspc config split_ratio 0.62
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc desktop ^1 -l monocle
bspc desktop ^2 -l monocle
bspc desktop ^5 -l monocle
bspc desktop ^6 -l monocle
bspc desktop ^9 -l monocle
bspc desktop ^10 -l monocle

# Rules
bspc rule -a xterm:Tiled desktop='^1' follow=on
bspc rule -a URxvt:Tmux desktop='^1' follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2' focus=on follow=on
bspc rule -a Subl3 desktop='^3'
bspc rule -a code-oss desktop='^3' focus=on follow=on
# bspc rule -a Thunar desktop='^4' state=pseudo_tiled
bspc rule -a Thunar desktop='^4' follow=on focus=on
bspc rule -a Thunar:Dialog state=floating center=true
bspc rule -a TelegramDesktop desktop='^5' follow=on
bspc rule -a discord desktop='^5' follow=on
bspc rule -a Gimp-2.10 desktop='^6'
bspc rule -a Inkscape desktop='^6'
bspc rule -a kdenlive desktop='^6'
bspc rule -a Audacious desktop='^7' state=floating follow=on focus=on
bspc rule -a Zathura desktop='^7' state=tiled follow=on
bspc rule -a Xreader desktop='^7' state=tiled follow=on
bspc rule -a '*:libreoffice' desktop='^8' state=tiled
bspc rule -a '*:soffice' desktop='^8'
bspc rule -a 'Wps' desktop='^8'
bspc rule -a 'Et' desktop='^8'
bspc rule -a 'Wpp' desktop='^8'
bspc rule -a 'Wpspdf' desktop='^8'
bspc rule -a Gnome-chess desktop='^9'
bspc rule -a teeworlds desktop='^9'
bspc rule -a Steam desktop='^9' state=floating
bspc rule -a "VirtualBox Manager" desktop='^10'
bspc rule -a 'MongoDB Compass' desktop='^9'

bspc rule -a Tint2 border=off manage=off layer=above state=floating
# bspc rule -a Mylaunchpad border=off manage=off
bspc rule -a '*:Kunst' sticky=on layer=below border=off focus=off
# bspc rule -a Sxiv:Kunst sticky=on layer=below border=off focus=off manage=off rectangle=250x250+1055+60
